{
 "title": "query frontend sim",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(loadgen_latency_bucket{tenant=~'heavy-user.*'}[1m])) by (le, tenant))",
     "legendFormat": ".99-{{tenant}}"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(loadgen_latency_bucket{tenant=~'heavy-user.*'}[1m])) by (le, tenant))",
     "legendFormat": ".9-{{tenant}}"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(loadgen_latency_bucket{tenant=~'heavy-user.*'}[1m])) by (le, tenant))",
     "legendFormat": ".5-{{tenant}}"
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(loadgen_latency_bucket{tenant=~'light-user.*'}[1m])) by (le, tenant))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(loadgen_latency_bucket{tenant=~'light-user.*'}[1m])) by (le, tenant))",
     "legendFormat": ".9."
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(loadgen_latency_bucket{tenant=~'light-user.*'}[1m])) by (le, tenant))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(loadgen_latency_bucket{tenant=~'intermittent-user.*'}[1m])) by (le, tenant))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(loadgen_latency_bucket{tenant=~'intermittent-user.*'}[1m])) by (le, tenant))",
     "legendFormat": ".9."
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(loadgen_latency_bucket{tenant=~'intermittent-user.*'}[1m])) by (le, tenant))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loadgen_latency_count[1m])",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "queue len",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cortex_query_frontend_queue_length"
    }
   ]
  },
  {
   "title": "time in queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(cortex_query_frontend_queue_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(cortex_query_frontend_queue_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(cortex_query_frontend_queue_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": ".5"
    }
   ]
  }
 ]
}