apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: registry.local:5000/sim-frontend:latest
        imagePullPolicy: Always
        command: ["./app"]
        ports:
        - containerPort: 3100
          name: http-metrics
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend
spec:
  ports:
  - name: http
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    name: frontend